[Sign]
LOGO = '''
  ______ _  __   __         ______       __   __             
 /_  __/(_)/ /_ / /___     / ____/___   / /_ / /_ ___   _____
  / /  / // __// // _ \   / / __ / _ \ / __// __// _ \ / ___/
 / /  / // /_ / //  __/  / /_/ //  __// /_ / /_ /  __// /    
/_/  /_/ \__//_/ \___/   \____/ \___/ \__/ \__/ \___//_/     
                                                             
By WeepingDogel
'''
Version = "v 2.1.0"

[Main]
URLLIST = "list.txt"
[headers]
User-Agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'

[BatchMode]
Turn_on = false

[Language]
# lang="en_US" is set  up to English
# lang="zh_CN" is set  up to Chinese 中文
lang = "en_US"
