[Sign]
LOGO = '''
  ______ _  __   __         ______       __   __             
 /_  __/(_)/ /_ / /___     / ____/___   / /_ / /_ ___   _____
  / /  / // __// // _ \   / / __ / _ \ / __// __// _ \ / ___/
 / /  / // /_ / //  __/  / /_/ //  __// /_ / /_ /  __// /    
/_/  /_/ \__//_/ \___/   \____/ \___/ \__/ \__/ \___//_/     
                                                             
By WeepingDogel
'''
[headers]
User-Agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'

[Proxy]
# Beta feature.
# Type your proxy address here.
Enable = true
socks5 = 'socks5h://127.0.0.1:1089'
http = 'http://127.0.0.1:8889'
